"""Изменение названия поля created_id на created_on

Revision ID: 5837188decca
Revises: cdbf669c0b40
Create Date: 2024-05-07 11:04:44.078819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5837188decca'
down_revision: Union[str, None] = 'cdbf669c0b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'updated_id')
    op.drop_column('tasks', 'created_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_id', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('updated_id', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'updated_on')
    op.drop_column('tasks', 'created_on')
    # ### end Alembic commands ###
