"""initial

Revision ID: f6ddf7359a3a
Revises: cecfec24d54d
Create Date: 2024-05-07 10:55:14.629731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ddf7359a3a'
down_revision: Union[str, None] = 'cecfec24d54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=1), nullable=True),
    sa.Column('result', sa.Numeric(), nullable=False),
    sa.Column('created_id', sa.DateTime(), nullable=True),
    sa.Column('updated_id', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
